### ISSUE TITLE
Form missing from "add a new example" page

### ISSUE THREAD

**Issue by ehelminen** [cogdog/ds106bank#13]
I just started playing with this theme today, and followed the directions as well as I could. The only thing that's not working for me so far is the "Add a new example" page. Wondering how I modify, or what I might be missing.

The page is here: http://dlc.middcreate.net/tinygig/add-example/. I'm looking at it using Chrome.

I've set the template for the page to be "Submit Response/Tutorial Form," and on the Assignment Bank Options page, I've set the "Page for Adding Examples/Tutorials" to be the "Add a New Example" page.

I have text on the page as well, and nothing shows up at all. Any help?

Thanks!

**Comment by cogdog** [comment]
My instructions are a bit unclear here, I will update. This page template should never be viewed as a plain page (it is supposed to have a message if directly loaded). 

It is used instead from one of your single gig pages from the "Add a Response" or "Add a Tutorial", e.g. http://dlc.middcreate.net/tinygig/add-example/?aid=28&typ=ex -- to work, it needs these paramaters which tell the page which assignment it is in response to and whether it is a response or a tutorial

If you are looking for the page / form to add a new "Gig" you want to create a page using the template for `Submit Thing Form`
