### ISSUE TITLE
display order sorting & date created

### ISSUE THREAD

**Issue by econproph** [cogdog/ds106bank#14]
I'm trying to change the display order sort but none of the three options really works for me (count, date created, or title).   I only have ~8 types, so I could force it to the order I want if I could change the date created for each type.   

I'm going to look in the database to see if I can easily see the date and just change it there, but if you have any suggestions I'm open.  This is likely a one-time or at most 1-2 times per year edit.

**Comment by cogdog** [comment]
You want an arbitrary order? Usually I would try forcing it with the titles, like using integers as leading character.

If I was fancy it would be a drag and drop interface.

I could look at adding an ordering field like pages do in WP.

**Comment by econproph** [comment]
Ordering field would be nice, but likely not worth it unless others want it.  I just got it to look the way I want by renaming a few titles.  
Thanks.
