### ISSUE TITLE
Page template error

### ISSUE THREAD

**Issue by eduToolkit** [cogdog/ds106bank#16]
The page templates "Submit thing form" (https://enrichedscience.edcamp.se/add-assignment/) and "Submit Example/Tutorial Form" (https://enrichedscience.edcamp.se/add-example/) returns with error code "HTTP ERROR 500"
Maybe I'm doing something wrong, but tried several installations in different domain...

**Comment by cogdog** [comment]
Sorry to hear that, but Error 500 just indicates possible php error. What would help is checking your servers error log which will contain more specific information about the error.

Also, you should never have a public link to "Submit Example/Tutorial Form" (https://enrichedscience.edcamp.se/add-example/) that url dies nothing; it needs to be clicked from a single assignment (it requires extra URL parameters that identify which thing it is associated with).

I'm running the theme on several sites now w/o any issues, including ones on PHP 7.

I'd like to help but would need more detailed information.
