### ISSUE TITLE
change styling on display of Example URL link

### ISSUE THREAD

**Issue by econproph** [cogdog/ds106bank#7]
I need to alter the styling of the display of the "Example URL" field in the page assignment details page.  It looks like it's probably regular bold centered.  An H3 or so would be nice.   Any tips on where in the CSS to change this?   Also wondering if maybe the URL when displayed could show an oEmbed preview of the link's page?

**Comment by cogdog** [comment]
You don't want to edit the CSS, but add CSS that overrides it, so this would go into the ds106bank.css file as additional styles (I put a comment in the top to suggest a place to insert). You should make sure you have a copy somewhere of what you use, as future updates will overwrite this file.

To style the heading (in bold):

```
#examplemedia strong {
    font-size: 20px;
    font-color: pink;
}
```

To center the heading and URL:

```
.example-url {
    text-align: center;
}
```

To style the link:

```
.example-url a {
    font-size: 18px;
}
```

It already has the feature to do a media embed, if the URL points to something Wordpress can autoembed -YouTube, vimeo, twitter, soundcloud, flickr- this code in functions.php shows what URLs we autoembed:

```
	$allowed_embeds = array(
					'youtube.com/watch?',
					'youtu.be',
					'flickr.com/photos',
					'flic.kr',
					'vimeo.com', 
					'soundcloud.com',
					'instagram.com',
					'twitter.com',
					'vine.co',
					'imgur.com',
					'animoto.com'
	);

```


See these examples

http://udg.theagoraonline.net/bank/assignments/message-acapella-style

http://udg.theagoraonline.net/bank/assignments/mood-tone-generator
