### ISSUE TITLE
Wordfence firewall issue

### ISSUE THREAD

**Issue by emerika** [cogdog/ds106bank#8]
It seems like the wordfence firewall is unhappy with how you're submitting the form for adding new makes, etc. I thought i saw a message mentioning jquery out ajax. 

It throws a 403 and says something like unsafe operation . 

For now I've disabled the firewall, but I think it's possible to tune the firewall to allow it to work without changes on your end.

**Comment by cogdog** [comment]
Bizarre. The submission forms don't use ajax to submit, it's standard Wordpress / nonce stuff. I'm not sure if you are using a more recent version, I do have a few jquery libraries to load a light box script for previews.

I will try out Wordfence on a test site to see if I can reproduce.
