### ISSUE TITLE
Remove sidebars?  

### ISSUE THREAD

**Issue by econproph** [cogdog/ds106bank#9]
Hey @CogDog!   THis is likely not an issue so much as an "it's obvious but apparently not to me" thing.  
We've got a DS106 theme install and we want to do away completely with any sidebars or widget areas. I want full width on all pages.   We're navigating purely from menu.   
but I'm not seeing how to do that.   Any help?

jim

**Comment by cogdog** [comment]
If you are talking about Pages content type, then it's built into the parent bootstrap theme, there is a template for Full Width:

![page-w](https://cloud.githubusercontent.com/assets/463038/22083526/b5747188-dd89-11e6-8f2a-56bf5c0428e2.jpg)

If you are talking about posts, you should get this `single.php` template and put it inside with ds106banker theme directory- it overrides the parent theme with a pull page width and no sidebar.

https://gist.github.com/cogdog/d9c4395e35710233a9238fd00c5e00ca
